name: 'sonatype-fortify-scan'
description: 'sca and ast scan'
inputs:
  scan-targets:
    description: 'folder/files to scan for sontype'
    required: true
  sonatype_server_url:
    description: ''
    required: true
  sonatype_username:
    description: ''
    required: true
  sonatype_password:
    description: ''
    required: true
  sonatype_app_id:
    description: ''
    required: true
  fod_tenant:
    description: ''
    required: true
  fod_user:
    description: ''
    required: true
  fod_pat:
    description: ''
    required: true
  fod_client_id:
    description: ''
    required: true
  fod_client_secret:
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sonatype Evaluate
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: ${{ inputs.sonatype_server_url }}
        username: ${{ inputs.sonatype_username }}
        password: ${{ inputs.sonatype_password }}
        application-id: ${{ inputs.sonatype_app_id }}
        scan-targets: '${{ inputs.scan-targets }}'

    - name: Log evaluate action output
      run: echo "${{ steps.evaluate.outputs.scan-id }} ${{ steps.evaluate.outputs.report-url }}"
      shell: bash

    - name: Run Fortify on Demand SAST & SCA Scan
      uses: fortify/github-action@v2
      with:
        sast-scan: true
        debricked-sca-scan: true
      env:
        FOD_URL: https://ams.fortify.com
        FOD_TENANT: ${{inputs.fod_tenant}}
        FOD_USER: ${{inputs.fod_user}}
        FOD_PASSWORD: ${{inputs.fod_pat}}
        FOD_CLIENT_ID: ${{inputs.fod_client_id}}
        FOD_CLIENT_SECRET: ${{inputs.fod_client_secret}}
